include:
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "base.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/check-commit/lint-commit.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/shell-lint.yml"
